### ISSUE TITLE
pylint error:  no such module

### ISSUE THREAD

**Issue by pgdr** [FriskByBergen/RPiParticle#112]
@joakim-hove do you understand these errors?

```
18:33:12 pi fby_client[..]: ************* Module bin/fby_client
18:33:12 pi fby_client[..]: F:  1, 0: No module named bin/fby_client (fatal)
18:33:12 pi fby_client[..]: ENo config file found, using default configuration
18:33:13 pi fby_client[..]: ************* Module lib/ts.py
18:33:13 pi fby_client[..]: F:  1, 0: No module named lib/ts.py (fatal)
18:33:13 pi fby_client[..]: E.
18:33:13 pi fby_client[..]: ======================================================================
18:33:13 pi fby_client[..]: ERROR: test_binaries (test_pylint.PylintTest)
18:33:13 pi fby_client[..]: ----------------------------------------------------------------------
18:33:13 pi fby_client[..]: Traceback (most recent call last):
18:33:13 pi fby_client[..]: File "/tmp/tmpaGUF18/tests/test_pylint.py", line 31, in test_binaries
18:33:13 pi fby_client[..]: exit_code = subprocess.check_call(["pylint" , "-E", prog])
18:33:13 pi fby_client[..]: File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
18:33:13 pi fby_client[..]: raise CalledProcessError(retcode, cmd)
18:33:13 pi fby_client[..]: CalledProcessError: Command '['pylint', '-E', 'bin/fby_client']' returned non-zero exit status 1
18:33:13 pi fby_client[..]: ======================================================================
18:33:13 pi fby_client[..]: ERROR: test_library (test_pylint.PylintTest)
18:33:13 pi fby_client[..]: ----------------------------------------------------------------------
18:33:13 pi fby_client[..]: Traceback (most recent call last):
18:33:13 pi fby_client[..]: File "/tmp/tmpaGUF18/tests/test_pylint.py", line 47, in test_library
18:33:13 pi fby_client[..]: exit_code = subprocess.check_call(["pylint" , "-E", lib])
18:33:13 pi fby_client[..]: File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
18:33:13 pi fby_client[..]: raise CalledProcessError(retcode, cmd)
18:33:13 pi fby_client[..]: CalledProcessError: Command '['pylint', '-E', 'lib/ts.py']' returned non-zero exit status 1
18:33:13 pi fby_client[..]: ----------------------------------------------------------------------
```

**Comment by joakim-hove** [comment]
I think you must invoke the tests as 'tests/run_tests' - I.e. there are
some hardcoded path relation assumptions?



27. feb. 2017 22:31 skrev "Pål Grønås Drange" <notifications@github.com>:

**Comment by pgdr** [comment]
Fixed
