### ISSUE TITLE
Server log flooding

### ISSUE THREAD

**Issue by pgdr** [FriskByBergen/RPiParticle#59]
I unplugged the sensor for 15 minutes and it flooded the server with logs (~2000 of them?)

We should probably do something smarter here.

```
Traceback (most recent call last):
  File "/usr/local/friskby/bin/fby_client", line 84, in main
    data = sampler.collect( )
  File "/usr/local/friskby/lib/sampler.py", line 17, in collect
    values = self.reader.read( )
  File "/usr/local/friskby/lib/sds011.py", line 24, in read
    s = self.device.read(1)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 460, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected?)')
SerialException: device reports readiness to read but returned no data (device disconnected?)
```

**Comment by joakim-hove** [comment]
> We should probably do something smarter here.

Yes - I fully agree. Possible PR here: https://github.com/FriskByBergen/RPiParticle/pull/60. Merge if like it[1].

[1]: I have tried to grant you the necessary permissions.
