### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by pgdr** [FriskByBergen/RPiParticle#94]
Ps (prescript): we should configure the client to restart on failure in systemd.

```
03:27:00 pi fby_client[716]: DeviceConfig.logMessage: {"device_id": "MYDEVICEID", "key": "MYSECRETKEY", "long_
03:27:20 pi fby_client[716]: Traceback (most recent call last):
03:27:20 pi fby_client[716]: File "/usr/local/friskby/bin/fby_client", line 148, in <module>
03:27:20 pi fby_client[716]: fby.run()
03:27:20 pi fby_client[716]: File "/usr/local/friskby/bin/fby_client", line 123, in run
03:27:20 pi fby_client[716]: self._config.logMessage('Exception caught: "%s".' % err_msg, long_msg = "".join( tb_list ))
03:27:20 pi fby_client[716]: File "/usr/local/friskby/lib/device_config.py", line 152, in logMessage
03:27:20 pi fby_client[716]: headers = headers )
03:27:20 pi fby_client[716]: File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
03:27:20 pi fby_client[716]: return request('post', url, data=data, json=json, **kwargs)
03:27:20 pi fby_client[716]: File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
03:27:20 pi fby_client[716]: return session.request(method=method, url=url, **kwargs)
03:27:20 pi fby_client[716]: File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
03:27:20 pi fby_client[716]: resp = self.send(prep, **send_kwargs)
03:27:20 pi fby_client[716]: File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
03:27:20 pi fby_client[716]: r = adapter.send(request, **kwargs)
03:27:20 pi fby_client[716]: File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
03:27:20 pi fby_client[716]: raise ConnectionError(err, request=request)
03:27:20 pi fby_client[716]: requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
03:27:20 pi systemd[1]: friskby.service: main process exited, code=exited, status=1/FAILURE
03:27:20 pi systemd[1]: Unit friskby.service entered failed state.
```

**Comment by joakim-hove** [comment]
It is the logging of an exception which creates an exception (Exceptions all the way down ....)
